// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_WEB_API_KEY'] ?? 'your-web-api-key',
    appId: dotenv.env['FIREBASE_WEB_APP_ID'] ?? 'your-web-app-id',
    messagingSenderId: dotenv.env['FIREBASE_MESSAGING_SENDER_ID'] ?? 'your-sender-id',
    projectId: dotenv.env['FIREBASE_PROJECT_ID'] ?? 'your-project-id',
    authDomain: dotenv.env['FIREBASE_AUTH_DOMAIN'] ?? 'your-project-id.firebaseapp.com',
    storageBucket: dotenv.env['FIREBASE_STORAGE_BUCKET'] ?? 'your-project-id.appspot.com',
  );

  static FirebaseOptions get android => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_ANDROID_API_KEY'] ?? 'your-android-api-key',
    appId: dotenv.env['FIREBASE_ANDROID_APP_ID'] ?? 'your-android-app-id',
    messagingSenderId: dotenv.env['FIREBASE_MESSAGING_SENDER_ID'] ?? 'your-sender-id',
    projectId: dotenv.env['FIREBASE_PROJECT_ID'] ?? 'your-project-id',
    storageBucket: dotenv.env['FIREBASE_STORAGE_BUCKET'] ?? 'your-project-id.appspot.com',
  );

  static FirebaseOptions get ios => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_IOS_API_KEY'] ?? 'your-ios-api-key',
    appId: dotenv.env['FIREBASE_IOS_APP_ID'] ?? 'your-ios-app-id',
    messagingSenderId: dotenv.env['FIREBASE_MESSAGING_SENDER_ID'] ?? 'your-sender-id',
    projectId: dotenv.env['FIREBASE_PROJECT_ID'] ?? 'your-project-id',
    storageBucket: dotenv.env['FIREBASE_STORAGE_BUCKET'] ?? 'your-project-id.appspot.com',
    iosBundleId: dotenv.env['IOS_BUNDLE_ID'] ?? 'com.yourcompany.yourapp',
  );

}