// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
    apiKey: dotenv.isInitialized
        ? (dotenv.env['FIREBASE_WEB_API_KEY'] ?? 'your-web-api-key')
        : 'your-web-api-key',
    appId: dotenv.isInitialized
        ? (dotenv.env['FIREBASE_WEB_APP_ID'] ?? 'your-web-app-id')
        : 'your-web-app-id',
    messagingSenderId: dotenv.isInitialized
        ? (dotenv.env['FIREBASE_MESSAGING_SENDER_ID'] ?? 'your-sender-id')
        : 'your-sender-id',
    projectId: dotenv.isInitialized
        ? (dotenv.env['FIREBASE_PROJECT_ID'] ?? 'your-project-id')
        : 'your-project-id',
    authDomain: dotenv.isInitialized
        ? (dotenv.env['FIREBASE_AUTH_DOMAIN'] ??
              'your-project-id.firebaseapp.com')
        : 'your-project-id.firebaseapp.com',
    storageBucket: dotenv.isInitialized
        ? (dotenv.env['FIREBASE_STORAGE_BUCKET'] ??
              'your-project-id.appspot.com')
        : 'your-project-id.appspot.com',
  );

  static FirebaseOptions get android => FirebaseOptions(
    apiKey: dotenv.isInitialized
        ? (dotenv.env['FIREBASE_ANDROID_API_KEY'] ??
              'AIzaSyDIRPwrWHZ5aVfU4WSEuUj7WtS237z5DO4')
        : 'AIzaSyDIRPwrWHZ5aVfU4WSEuUj7WtS237z5DO4',
    appId: dotenv.isInitialized
        ? (dotenv.env['FIREBASE_ANDROID_APP_ID'] ??
              '1:89886471430:android:0daf63b7dc13a70af75a87')
        : '1:89886471430:android:0daf63b7dc13a70af75a87',
    messagingSenderId: dotenv.isInitialized
        ? (dotenv.env['FIREBASE_MESSAGING_SENDER_ID'] ?? '89886471430')
        : '89886471430',
    projectId: dotenv.isInitialized
        ? (dotenv.env['FIREBASE_PROJECT_ID'] ?? 'pega-attendence')
        : 'pega-attendence',
    storageBucket: dotenv.isInitialized
        ? (dotenv.env['FIREBASE_STORAGE_BUCKET'] ??
              'pega-attendence.firebasestorage.app')
        : 'pega-attendence.firebasestorage.app',
  );

  static FirebaseOptions get ios => FirebaseOptions(
    apiKey: dotenv.isInitialized
        ? (dotenv.env['FIREBASE_IOS_API_KEY'] ??
              'AIzaSyAIUqXvYg7nKrYGLBSQdnrAHjEA3iEXUyE')
        : 'AIzaSyAIUqXvYg7nKrYGLBSQdnrAHjEA3iEXUyE',
    appId: dotenv.isInitialized
        ? (dotenv.env['FIREBASE_IOS_APP_ID'] ??
              '1:89886471430:ios:97fd9294bbf99fccf75a87')
        : '1:89886471430:ios:97fd9294bbf99fccf75a87',
    messagingSenderId: dotenv.isInitialized
        ? (dotenv.env['FIREBASE_MESSAGING_SENDER_ID'] ?? '89886471430')
        : '89886471430',
    projectId: dotenv.isInitialized
        ? (dotenv.env['FIREBASE_PROJECT_ID'] ?? 'pega-attendence')
        : 'pega-attendence',
    storageBucket: dotenv.isInitialized
        ? (dotenv.env['FIREBASE_STORAGE_BUCKET'] ??
              'pega-attendence.firebasestorage.app')
        : 'pega-attendence.firebasestorage.app',
    iosBundleId: dotenv.isInitialized
        ? (dotenv.env['IOS_BUNDLE_ID'] ?? 'com.matrimpathak.attendenceFlutter')
        : 'com.matrimpathak.attendenceFlutter',
  );
}
